Repository asciidoctor/docker-asciidoctor, pull requests merged in 2022-02, with the labels that each got.

#237 Add CVE scan pipeline as scheduled nightly
  .github/containerscan/allowedlist.yaml
  .github/workflows/cve-scan.yml
Labels: chore, dependencies, skip-changelog

#236 Update README.adoc to include example for asciidoctor-mathematical
  README.adoc
Labels: chore, documentation

#242 Add Trivy CVE scan info to README
  .github/containerscan/allowedlist.yaml
  README.adoc
Labels: documentation
